AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-layer-sam
  create lambda layer using sam


Globals:
  Function:
    Timeout: 3

Resources:
  Pynamodb:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pynamodb-layer
      ContentUri: pynamodb/package.zip
      CompatibleRuntimes:
        - python3.8
  PynamoLayerPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref Pynamodb
      Principal: "*"
  Pandas:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pandas-layer
      ContentUri: pandas/package.zip
      CompatibleRuntimes:
        - python3.8
  PandasLayerPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref Pandas
      Principal: "*"
  Line:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: line-layer
      ContentUri: line/package.zip
      CompatibleRuntimes:
        - python3.8
  LineLayerPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref Line
      Principal: "*"
  CloudSearch:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: cloudsearch-layer
      ContentUri: cloudsearch/package.zip
      CompatibleRuntimes:
        - python3.8
  CloudSearchLayerPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref CloudSearch
      Principal: "*"

Outputs:
  PynamoArn:
    Value: !Ref Pynamodb
  PandasArn:
    Value: !Ref Pandas
  LineArn:
    Value: !Ref Line
  CloudSearchArn:
    Value: !Ref CloudSearch
